DjangoLevel5/MyWebsite/MyWebsite/urls.py
from django.contrib import admin
from django.urls import path,include
from basicApp import views

urlpatterns = [
    path('',views.index,name="index"),
    path('basicApp/',include('basicApp.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout,name='logout'),
    # path('') 
]

DjangoLevel5/MyWebsite/basicApp/urls.py
# from django.conf.urls import url
from django.urls import path
from basicApp import views

# Template URLS!
app_name = 'basicApp'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login')

]

DjangoLevel5/MyWebsite/basicApp/models.py
from django.db import models
from django.contrib.auth.models import User #import User that is there in admin 

# Create your models here.
class UserProfileInfo(models.Model):
    #Create relationship with User model (and not inheriting directly) 
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)
    # additional attributes (basic ones are already there in 'User' model)
    portfolio_site = models.URLField(blank=True, max_length=200)
    profile_pic = models.ImageField(blank=True, upload_to='profile_pics')

    def __str__(self):
        return self.user.username
    

DjangoLevel5/MyWebsite/basicApp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicApp.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(required=True,widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ("username","email","password")

class UserProfileInfoForm(forms.ModelForm):    
    # Editing not needed. So not needed to write again.
    # portfolio = forms.URLField(, required=False)
    # picture = forms.ImageField(required=False)
    class Meta: #connects this form to its model
        model = UserProfileInfo
        fields = ("portfolio_site","profile_pic")

DjangoLevel5/MyWebsite/basicApp/views.py
from django.shortcuts import render
from basicApp.forms import UserForm,UserProfileInfoForm
#
from django.urls import reverse  # change to django.url if not working
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def index(request):
    return render(request,'basicApp/index.html')

def register(request):
    registered=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form= UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid() :
            user = user_form.save() #getting form data to database
            user.set_password(user.password) # hashing done
            user.save() #saving the password

            profile = profile_form.save(commit=False) #not saving directly to D.B. to check presemce of profile pic
            profile.user = user #setting the one to one relationship with the User class

            if 'profile_pic' in request.FILES: #use request.FILES to access any kind of file submitted
                profile.profile_pic = request.FILES['profile_pic'] 
            
            profile.save()

            registered=True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    
    return render(request,'basicApp/registration.html',
                            {'user_form':user_form,
                                 'profile_form':profile_form,
                                 'registered':registered})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    
def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("login failed")
            return HttpResponse("Invalid login details!")
    else:
        return render(request,'basicApp/login.html', {})

DjangoLevel5/MyWebsite/templates/basicApp/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
            <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'basicApp:register' %}">Register</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">logout</a></li>
                    {% else %}
                    <li><a class="navbar-link" href="{% url 'basicApp:user_login' %}">Login</a></li>
                    {% endif %}               
                </ul>
        </div>
            </nav>
        <div class="container">
                {% block body_block %}
                {% endblock body_block %}
        </div>      
</body>
</html>

DjangoLevel5/MyWebsite/templates/basicApp/index.html
{% extends 'basicApp/base.html' %}

{% block body_block %}
<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>
{% endblock body_block %}

DjangoLevel5/MyWebsite/templates/basicApp/login.html
{% extends 'basicApp/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basicApp:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password" id="">

        <input type="submit" value="Login">
    </form>
</div>
{% endblock body_block %}

DjangoLevel5/MyWebsite/templates/basicApp/registration.html
{% extends 'basicApp/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
        <h1>Thank You for registering</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" value="Register">
    </form>
    {% endif %}
</div>

{% endblock body_block %}